os: linux
dist: xenial
language: python
python: "3.7"
install:
  - pip install conan
before_script:
  - conan user
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
script:
  - mkdir build && cd build
  - conan install ..
  - cmake ..
  - cmake --build .
  - bin/folly_example
